version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run:
          name: 'Install Dependecies'
          command: npm install --save-dev firebase-tools
      - run:
          name: Deploy Master to Firebase
          command: node_modules/.bin/firebase deploy --only hosting --project "$FIREBASE_PJ" --token=$FIREBASE_TOKEN